version: '3.3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 2022:27017
    volumes:
      - db-data:/data/db

  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    ports:
      - 2023:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home

  redis:
    image: redis
    restart: always
    ports:
      - "2024:6379"
    hostname: redis

  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "2025:8081"

volumes:
  db-data:
  jenkins-data:
