version: '3.3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 2022:27017
    volumes:
      - db-data:/data/db

volumes:
  db-data:
  jenkins-data:
